name: dms
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8.5
  - pandas
  - numpy
  - python-lmdb
  - pytorch::pytorch
  - nvidia::cudatoolkit=11.3
  - torchvision
  - pip
  - pip:
      - git+https://github.com/microsoft/protein-sequence-models.git
      - mlflow
      - scikit-learn
      - blosum
      - matplotlib
      - fair-esm
      - tqdm
