name: dms
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8.5
  - pandas
  - numpy
  - python-lmdb
  - pytorch::pytorch
  - nvidia::cudatoolkit=11.3
  - torchvision
  - pip
  - pip:
      - sequence-models
      - mlflow
      - scikit-learn
      - blosum
      - matplotlib
